name: stadyl_analysis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.3.1
  - r-haven
  - r-psych
  - r-dplyr
  - r-car
  - r-interactions
  - r-ggplot2
  - r-ggfortify
  - r-lm.beta
  - r-reghelper
  - r-hmisc
  - r-devtools
  - r-rcpp
  - r-rlang
  - r-rcurl
  - r-tidyverse
  - pandoc
  - pip
  - pip:
      - jupyter
